// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzXCwHKSxAZGxkxuXObOIOwe7S6caUaZY',
    appId: '1:597022047813:web:dbd3e7ef47104a078ead2c',
    messagingSenderId: '597022047813',
    projectId: 'astra-one-step-ahead',
    authDomain: 'astra-one-step-ahead.firebaseapp.com',
    storageBucket: 'astra-one-step-ahead.firebasestorage.app',
    measurementId: 'G-DGS3JZXTH8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVZQcszhYa4qJ99f7D0_UeorynCs-0zns',
    appId: '1:597022047813:android:f0386f5ed58a816e8ead2c',
    messagingSenderId: '597022047813',
    projectId: 'astra-one-step-ahead',
    storageBucket: 'astra-one-step-ahead.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXdEyz0HSp5L99RRf-EjsDv_oTXz76ILE',
    appId: '1:597022047813:ios:72e2b5a401b219f08ead2c',
    messagingSenderId: '597022047813',
    projectId: 'astra-one-step-ahead',
    storageBucket: 'astra-one-step-ahead.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXdEyz0HSp5L99RRf-EjsDv_oTXz76ILE',
    appId: '1:597022047813:ios:72e2b5a401b219f08ead2c',
    messagingSenderId: '597022047813',
    projectId: 'astra-one-step-ahead',
    storageBucket: 'astra-one-step-ahead.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzXCwHKSxAZGxkxuXObOIOwe7S6caUaZY',
    appId: '1:597022047813:web:c0b465dde75860008ead2c',
    messagingSenderId: '597022047813',
    projectId: 'astra-one-step-ahead',
    authDomain: 'astra-one-step-ahead.firebaseapp.com',
    storageBucket: 'astra-one-step-ahead.firebasestorage.app',
    measurementId: 'G-V8WCFLJ433',
  );
}
